### ISSUE TITLE
Documentation question, 

### ISSUE THREAD

**Issue by auzieman** [lynxman/hiera-consul#6]
Giving this a shot using
```bash
pe-hiera-1.3.4.1-1.pe.el6.noarch
pe-puppet-3.7.2.2-1.pe.el6.noarch
```
Default setup, simply ran puppet forge, mod'd heir.yaml against a working consul (though not finalized) and I'm getting this error about loading backends.  Even moved your module from environments/production/ to simply modules/ in puppets path.. 

Installed module here,
```bash
[root@puppet ~]# ls /etc/puppetlabs/puppet/modules/hiera_consul/
checksums.json  Gemfile  lib  LICENSE  metadata.json  Rakefile  README.md
```
Example hiera.yaml
```yaml
---
:backends:
  - consul
  - yaml

:consul:
  :host: 127.0.0.1
  :port: 8500
  :paths:
   - /v1/catalog/service
   - /v1/catalog/services
   - /v1/catalog/node
   - /v1/catalog/nodes
```
Yet,, 

```bash 
[root@puppet ~]# hiera dns
WARN: 2015-03-30 17:43:05 +0000: Cannot load backend consul: cannot load such file -- hiera/backend/consul_backend
nil

[root@puppet ~]# curl http://localhost:8500/v1/catalog/service/dns?tag=bind[{"Node":"puppet.example.lan","Address":"192.168.33.10","ServiceID":"dns","ServiceName":"dns","ServiceTags":["bind"],"ServiceAddress":"","ServicePort":53}][root@puppet ~]#
DEBUG: 2015-03-30 17:38:13 +0000: Looking for data source global
```

Is this typical? I'm assuming I'm missing something obvious here, as I haven't attempted this before.  Also though you give some examples of using this inside puppet am correct about the command line right? (While I wait I'll give it a try with in notify or such like your examples)

**Comment by lynxman** [comment]
Hi,

This is due to the location of the hiera_consul module, it's in the puppet modules hierarchy so only puppet will be able to see it, calling hiera directly will cause an error.

**Comment by xiii** [comment]
Hi @auzieman , I suppose you want to debug from the CLI. I use this simple 'hack' in my vagrant dev env:

 I link /vagrant/puppet/modules/hiera_consul/lib/hiera/backend/consul_backend.rb in this directory /usr/share/ruby/vendor_ruby/hiera/backend/ and I can use hiera cli with consul backend. 

cheers
